"""
Bhumi Prajna - Load Synthetic Data into Database
Reads the synthetic CSVs generated by the training pipeline and inserts
them into historical_projects and historical_project_snapshots tables.
All records are clearly labelled is_synthetic=true.
"""

import asyncio
import sys
import os
import json
import uuid
from pathlib import Path
from datetime import datetime, timezone

import pandas as pd

sys.path.insert(0, str(Path(__file__).parent.parent))

from app.db.session import AsyncSessionLocal, engine, Base
from app.models.project import HistoricalProject, HistoricalProjectSnapshot, ModelVersion

DATA_DIR = Path(__file__).parent.parent / "models" / "training_data"
META_PATH = Path(__file__).parent.parent / "models" / "model_metadata.json"
MODEL_DIR = Path(__file__).parent.parent / "models"


async def load_synthetic_data():
    projects_csv = DATA_DIR / "synthetic_projects.csv"
    snapshots_csv = DATA_DIR / "synthetic_snapshots.csv"

    print("📂 Loading synthetic CSVs...")
    projects_df = pd.read_csv(projects_csv)
    snapshots_df = pd.read_csv(snapshots_csv)
    print(f"   {len(projects_df)} projects, {len(snapshots_df)} snapshots")

    async with AsyncSessionLocal() as session:
        # Check if already loaded
        from sqlalchemy import select, func
        count = (await session.execute(
            select(func.count()).select_from(HistoricalProject).where(HistoricalProject.is_synthetic == True)
        )).scalar()

        if count > 0:
            print(f"   ⏭  {count} synthetic projects already in DB — skipping")
        else:
            print("   Inserting historical projects...")
            for _, row in projects_df.iterrows():
                proj = HistoricalProject(
                    id=uuid.UUID(row["historical_project_id"]),
                    project_name=row["project_name"],
                    state=row["state"],
                    district=row["district"],
                    project_type=row["project_type"],
                    land_area=float(row["land_area"]),
                    affected_families=int(row["affected_families"]),
                    final_status=row["final_status"],
                    total_duration_days=int(row["total_duration_days"]) if pd.notna(row["total_duration_days"]) else None,
                    is_synthetic=True,
                    seed_version=row.get("seed_version", "v1.0-synthetic"),
                )
                session.add(proj)
            await session.flush()
            print(f"   ✅ {len(projects_df)} projects inserted")

            print("   Inserting historical snapshots...")
            batch = []
            for _, row in snapshots_df.iterrows():
                def safe_date(val):
                    if pd.isna(val) or val is None or str(val) == "nan":
                        return None
                    try:
                        from datetime import date
                        if isinstance(val, date):
                            return val
                        return pd.to_datetime(val).date()
                    except:
                        return None

                def safe_int(val):
                    if pd.isna(val): return None
                    return int(val)

                def safe_float(val):
                    if pd.isna(val): return None
                    return float(val)

                snap = HistoricalProjectSnapshot(
                    id=uuid.UUID(row["snapshot_id"]),
                    historical_project_id=uuid.UUID(row["historical_project_id"]),
                    snapshot_date=safe_date(row["snapshot_date"]),
                    current_stage=row["current_stage"],
                    next_stage=row["next_stage"] if pd.notna(row.get("next_stage")) else None,
                    # Approvals
                    approvals_required=safe_int(row.get("approvals_required", 0)),
                    approvals_completed=safe_int(row.get("approvals_completed", 0)),
                    approvals_pending=safe_int(row.get("approvals_pending", 0)),
                    approval_progress_pct=safe_float(row.get("approval_progress_pct", 0)),
                    oldest_pending_approval_days=safe_int(row.get("oldest_pending_approval_days")),
                    # Legal
                    legal_cases_total=safe_int(row.get("legal_cases_total", 0)),
                    legal_cases_pending=safe_int(row.get("legal_cases_pending", 0)),
                    legal_cases_resolved=safe_int(row.get("legal_cases_resolved", 0)),
                    disputed_land_area=safe_float(row.get("disputed_land_area", 0)),
                    oldest_pending_case_days=safe_int(row.get("oldest_pending_case_days")),
                    # Compensation
                    compensation_total_amount=safe_float(row.get("compensation_total_amount", 0)),
                    compensation_paid_amount=safe_float(row.get("compensation_paid_amount", 0)),
                    compensation_pending_amount=safe_float(row.get("compensation_pending_amount", 0)),
                    beneficiaries_eligible=safe_int(row.get("beneficiaries_eligible", 0)),
                    beneficiaries_compensated=safe_int(row.get("beneficiaries_compensated", 0)),
                    beneficiaries_pending=safe_int(row.get("beneficiaries_pending", 0)),
                    compensation_progress_pct=safe_float(row.get("compensation_progress_pct", 0)),
                    # Documentation
                    documents_required=safe_int(row.get("documents_required", 0)),
                    documents_submitted=safe_int(row.get("documents_submitted", 0)),
                    documents_verified=safe_int(row.get("documents_verified", 0)),
                    documents_incomplete=safe_int(row.get("documents_incomplete", 0)),
                    documentation_progress_pct=safe_float(row.get("documentation_progress_pct", 0)),
                    # Notifications
                    notifications_required=safe_int(row.get("notifications_required", 0)),
                    notifications_issued=safe_int(row.get("notifications_issued", 0)),
                    notifications_pending=safe_int(row.get("notifications_pending", 0)),
                    notification_progress_pct=safe_float(row.get("notification_progress_pct", 0)),
                    # Ownership
                    parcels_total=safe_int(row.get("parcels_total", 0)),
                    parcels_disputed=safe_int(row.get("parcels_disputed", 0)),
                    ownership_conflicts_pending=safe_int(row.get("ownership_conflicts_pending", 0)),
                    ownership_conflicts_resolved=safe_int(row.get("ownership_conflicts_resolved", 0)),
                    # R&R
                    rr_families_required=safe_int(row.get("rr_families_required", 0)),
                    rr_families_completed=safe_int(row.get("rr_families_completed", 0)),
                    rr_families_pending=safe_int(row.get("rr_families_pending", 0)),
                    rr_progress_pct=safe_float(row.get("rr_progress_pct", 0)),
                    # Possession
                    land_required_for_possession=safe_float(row.get("land_required_for_possession", 0)),
                    land_acquired_for_possession=safe_float(row.get("land_acquired_for_possession", 0)),
                    possession_progress_pct=safe_float(row.get("possession_progress_pct", 0)),
                    # Stakeholder
                    stakeholder_requests_raised=safe_int(row.get("stakeholder_requests_raised", 0)),
                    stakeholder_responses_received=safe_int(row.get("stakeholder_responses_received", 0)),
                    stakeholder_requests_pending=safe_int(row.get("stakeholder_requests_pending", 0)),
                    average_response_time_days=safe_float(row.get("average_response_time_days")),
                    # Coordination
                    departments_involved=safe_int(row.get("departments_involved", 0)),
                    coordination_requests_raised=safe_int(row.get("coordination_requests_raised", 0)),
                    coordination_requests_resolved=safe_int(row.get("coordination_requests_resolved", 0)),
                    coordination_requests_pending=safe_int(row.get("coordination_requests_pending", 0)),
                    average_coordination_response_days=safe_float(row.get("average_coordination_response_days")),
                    # Temporal
                    days_in_current_stage=safe_int(row.get("days_in_current_stage", 0)),
                    total_project_days=safe_int(row.get("total_project_days", 0)),
                    # Targets (training labels — separated from features)
                    next_stage_delayed_30d=safe_int(row.get("next_stage_delayed_30d")),
                    next_stage_delay_days=safe_int(row.get("next_stage_delay_days")),
                    next_stage_planned_completion_date=safe_date(row.get("next_stage_planned_completion_date")),
                    next_stage_actual_completion_date=safe_date(row.get("next_stage_actual_completion_date")),
                    is_synthetic=True,
                )
                batch.append(snap)

                if len(batch) >= 200:
                    session.add_all(batch)
                    await session.flush()
                    batch = []

            if batch:
                session.add_all(batch)
                await session.flush()
            print(f"   ✅ {len(snapshots_df)} snapshots inserted")

        # Register model version
        existing_mv = (await session.execute(
            select(ModelVersion).where(ModelVersion.model_version == "v1.0.0")
        )).scalar_one_or_none()

        if not existing_mv:
            with open(META_PATH) as f:
                meta = json.load(f)

            mv = ModelVersion(
                model_version="v1.0.0",
                model_type="LightGBM",
                training_dataset_version="synthetic-v1.0",
                feature_schema_version="v1.0",
                validation_metrics=meta.get("validation_metrics"),
                calibration_metrics=meta.get("validation_metrics", {}).get("calibration"),
                status="approved",
                notes="LightGBM selected over Logistic Regression baseline. "
                      "PR-AUC 0.9931. Synthetic data only — clearly labelled.",
                model_path=str(MODEL_DIR),
            )
            session.add(mv)
            print("   ✅ ModelVersion v1.0.0 registered")
        else:
            print("   ⏭  ModelVersion v1.0.0 already registered")

        await session.commit()
        print("\n✅ M2 DB load complete")


if __name__ == "__main__":
    asyncio.run(load_synthetic_data())
